package org.openphone.assistant.surface

import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.text.BasicTextField
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.LinearProgressIndicator
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateMapOf
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.semantics.Role
import androidx.compose.ui.semantics.contentDescription
import androidx.compose.ui.semantics.role
import androidx.compose.ui.semantics.semantics
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import org.json.JSONObject

/**
 * Renderer for the validated, bounded Surface V1 component registry.
 *
 * This code intentionally has no WebView, HTML, arbitrary color, absolute
 * positioning, remote URL, or runtime code path.
 */
@Composable
fun AdaptiveSurfaceView(
    surface: AdaptiveSurface,
    actionStatus: String,
    onAction: (String, JSONObject) -> Unit,
    onDismiss: () -> Unit,
    modifier: Modifier = Modifier,
) {
    val inputs = remember(surface.surfaceId, surface.revision) {
        mutableStateMapOf<String, Any>()
    }
    Column(
        modifier = modifier
            .fillMaxWidth()
            .clip(RoundedCornerShape(28.dp))
            .background(MaterialTheme.colorScheme.surface)
            .border(1.dp, Color(0xFF263246), RoundedCornerShape(28.dp))
            .padding(20.dp),
    ) {
        Row(verticalAlignment = Alignment.CenterVertically) {
            Column(modifier = Modifier.weight(1f)) {
                Text(
                    surface.title.ifBlank { "OpenPhone" },
                    color = MaterialTheme.colorScheme.onSurface,
                    style = MaterialTheme.typography.titleLarge,
                    fontWeight = FontWeight.SemiBold,
                )
                Text(
                    "Generated by ${surface.runtime} · ${surface.sensitivity}",
                    color = MaterialTheme.colorScheme.onSurfaceVariant,
                    style = MaterialTheme.typography.labelSmall,
                )
            }
            Text(
                "Close",
                color = MaterialTheme.colorScheme.onSurfaceVariant,
                modifier = Modifier
                    .clip(RoundedCornerShape(14.dp))
                    .clickable(onClick = onDismiss)
                    .semantics {
                        contentDescription = "Dismiss ${surface.title} surface"
                        role = Role.Button
                    }
                    .padding(8.dp),
            )
        }
        Spacer(Modifier.height(14.dp))
        Column(
            modifier = Modifier
                .fillMaxWidth()
                .verticalScroll(rememberScrollState()),
        ) {
            SurfaceNode(
                node = surface.body,
                inputs = inputs,
                onAction = { actionId ->
                    onAction(actionId, JSONObject(inputs.toMap()))
                },
            )
            if (actionStatus.isNotBlank()) {
                Text(
                    actionStatus,
                    color = MaterialTheme.colorScheme.onSurfaceVariant,
                    style = MaterialTheme.typography.labelMedium,
                    modifier = Modifier.padding(top = 14.dp),
                )
            }
        }
    }
}

@Composable
private fun SurfaceNode(
    node: SurfaceComponent,
    inputs: MutableMap<String, Any>,
    onAction: (String) -> Unit,
) {
    val children = node.array("children").components()
    val items = node.array("items").components()
    val spacing = spacing(node.string("spacing"))
    when (node.type()) {
        "column", "scroll", "list", "timeline" -> Column(
            modifier = Modifier.fillMaxWidth(),
            verticalArrangement = Arrangement.spacedBy(spacing),
        ) {
            (if (children.isNotEmpty()) children else items).forEach {
                SurfaceNode(it, inputs, onAction)
            }
        }

        "row" -> Row(
            modifier = Modifier.fillMaxWidth(),
            horizontalArrangement = Arrangement.spacedBy(spacing),
            verticalAlignment = Alignment.CenterVertically,
        ) {
            children.forEach { SurfaceNode(it, inputs, onAction) }
        }

        "spacer" -> Spacer(Modifier.height(spacing.coerceAtLeast(8.dp)))
        "divider" -> Box(
            Modifier
                .fillMaxWidth()
                .height(1.dp)
                .background(Color(0xFF263246)),
        )

        "text" -> SurfaceText(node)
        "icon" -> SurfaceIcon(node)
        "image" -> SafeImagePlaceholder(node)
        "badge" -> SurfaceBadge(node)
        "progress" -> LinearProgressIndicator(
            progress = { node.number("progress", 0.0).toFloat().coerceIn(0f, 1f) },
            modifier = Modifier
                .fillMaxWidth()
                .semantics {
                    contentDescription = node.string("content_description")
                        .ifBlank { "Progress" }
                },
            color = tone(node.string("tone")),
            trackColor = MaterialTheme.colorScheme.surfaceVariant,
        )

        "card" -> Column(
            modifier = Modifier
                .fillMaxWidth()
                .clip(RoundedCornerShape(20.dp))
                .background(MaterialTheme.colorScheme.surfaceVariant)
                .padding(if (node.string("density") == "compact") 12.dp else 16.dp),
            verticalArrangement = Arrangement.spacedBy(spacing.coerceAtLeast(8.dp)),
        ) {
            children.forEach { SurfaceNode(it, inputs, onAction) }
        }

        "list_item" -> SurfaceListItem(node, onAction)
        "button", "chip", "native_handoff", "confirmation" ->
            SurfaceButton(node, onAction)

        "choice_group" -> SurfaceChoices(node, inputs)
        "toggle" -> SurfaceToggle(node, inputs, onAction)
        "text_input" -> SurfaceTextInput(node, inputs)
        "capability_disclosure" -> SurfaceDisclosure(node)
        "error" -> SurfaceError(node)
    }
}

@Composable
private fun SurfaceText(node: SurfaceComponent) {
    val style = when (node.string("style")) {
        "title" -> MaterialTheme.typography.titleMedium
        "headline" -> MaterialTheme.typography.headlineSmall
        "caption" -> MaterialTheme.typography.labelMedium
        else -> MaterialTheme.typography.bodyLarge
    }
    Text(
        node.string("text"),
        color = tone(node.string("tone")),
        style = style,
        fontWeight = if (node.string("style") in setOf("title", "headline")) {
            FontWeight.SemiBold
        } else {
            FontWeight.Normal
        },
    )
}

@Composable
private fun SurfaceIcon(node: SurfaceComponent) {
    val glyph = when (node.string("icon")) {
        "calendar" -> "▣"
        "message" -> "✉"
        "notification" -> "◉"
        "person" -> "●"
        "phone" -> "⌕"
        "location" -> "⌖"
        "clock" -> "◷"
        "check" -> "✓"
        "warning" -> "!"
        "error" -> "×"
        "open" -> "↗"
        else -> "✦"
    }
    Text(
        glyph,
        color = tone(node.string("tone")),
        fontWeight = FontWeight.Bold,
        modifier = Modifier.semantics {
            contentDescription = node.string("content_description")
                .ifBlank { node.string("icon") }
        },
    )
}

@Composable
private fun SafeImagePlaceholder(node: SurfaceComponent) {
    Box(
        modifier = Modifier
            .fillMaxWidth()
            .height(132.dp)
            .clip(RoundedCornerShape(18.dp))
            .background(MaterialTheme.colorScheme.surfaceVariant)
            .semantics {
                contentDescription = node.string("content_description")
                    .ifBlank { "Phone-owned image artifact" }
            },
        contentAlignment = Alignment.Center,
    ) {
        Text("Image artifact", color = MaterialTheme.colorScheme.onSurfaceVariant)
    }
}

@Composable
private fun SurfaceBadge(node: SurfaceComponent) {
    Text(
        node.string("label").ifBlank { node.string("text") },
        color = Color.Black,
        style = MaterialTheme.typography.labelMedium,
        fontWeight = FontWeight.SemiBold,
        modifier = Modifier
            .clip(RoundedCornerShape(999.dp))
            .background(tone(node.string("tone")))
            .padding(horizontal = 10.dp, vertical = 5.dp),
    )
}

@Composable
private fun SurfaceListItem(node: SurfaceComponent, onAction: (String) -> Unit) {
    val actionId = node.string("action_id")
    val label = node.string("content_description")
        .ifBlank { listOf(node.string("title"), node.string("subtitle")).joinToString(". ") }
    Row(
        modifier = Modifier
            .fillMaxWidth()
            .clip(RoundedCornerShape(16.dp))
            .then(
                if (actionId.isNotBlank()) {
                    Modifier.clickable { onAction(actionId) }
                } else {
                    Modifier
                },
            )
            .semantics {
                contentDescription = label
                if (actionId.isNotBlank()) role = Role.Button
            }
            .padding(vertical = 12.dp, horizontal = 8.dp),
        verticalAlignment = Alignment.CenterVertically,
    ) {
        if (node.string("icon").isNotBlank()) {
            SurfaceIcon(SurfaceComponent.fromJson(JSONObject()
                .put("type", "icon")
                .put("icon", node.string("icon"))
                .put("content_description", node.string("icon"))))
            Spacer(Modifier.size(12.dp))
        }
        Column(modifier = Modifier.weight(1f)) {
            Text(
                node.string("title"),
                color = MaterialTheme.colorScheme.onSurface,
                style = MaterialTheme.typography.titleSmall,
                fontWeight = FontWeight.SemiBold,
            )
            if (node.string("subtitle").isNotBlank()) {
                Text(
                    node.string("subtitle"),
                    color = MaterialTheme.colorScheme.onSurfaceVariant,
                    style = MaterialTheme.typography.bodyMedium,
                )
            }
        }
        if (actionId.isNotBlank()) {
            Text("›", color = MaterialTheme.colorScheme.primary)
        }
    }
}

@Composable
private fun SurfaceButton(node: SurfaceComponent, onAction: (String) -> Unit) {
    val actionId = node.string("action_id")
    val label = node.string("label")
        .ifBlank { node.string("title").ifBlank { node.string("text") } }
    val danger = node.string("tone") == "danger" || node.type() == "confirmation"
    Text(
        label,
        color = if (danger) Color.White else Color.Black,
        fontWeight = FontWeight.SemiBold,
        modifier = Modifier
            .clip(RoundedCornerShape(if (node.type() == "chip") 999.dp else 18.dp))
            .background(if (danger) Color(0xFF8D2632) else MaterialTheme.colorScheme.primary)
            .clickable { onAction(actionId) }
            .semantics {
                contentDescription = node.string("content_description").ifBlank { label }
                role = Role.Button
            }
            .padding(horizontal = 16.dp, vertical = 11.dp),
    )
}

@Composable
private fun SurfaceChoices(node: SurfaceComponent, inputs: MutableMap<String, Any>) {
    val key = node.string("input_key")
    val options = node.array("options")
    Column(verticalArrangement = Arrangement.spacedBy(8.dp)) {
        if (node.string("label").isNotBlank()) {
            Text(node.string("label"), color = MaterialTheme.colorScheme.onSurface)
        }
        for (index in 0 until options.length()) {
            val option = options.optJSONObject(index) ?: continue
            val id = option.optString("id", "")
            val label = option.optString("label", "")
            val selected = inputs[key] == id
            Text(
                label,
                color = if (selected) Color.Black else MaterialTheme.colorScheme.onSurface,
                modifier = Modifier
                    .clip(RoundedCornerShape(999.dp))
                    .background(
                        if (selected) MaterialTheme.colorScheme.secondary
                        else MaterialTheme.colorScheme.surfaceVariant,
                    )
                    .clickable { inputs[key] = id }
                    .semantics {
                        contentDescription = "$label, ${if (selected) "selected" else "not selected"}"
                        role = Role.RadioButton
                    }
                    .padding(horizontal = 14.dp, vertical = 9.dp),
            )
        }
    }
}

@Composable
private fun SurfaceToggle(
    node: SurfaceComponent,
    inputs: MutableMap<String, Any>,
    onAction: (String) -> Unit,
) {
    val key = node.string("input_key")
    val initial = node.bool("checked", false)
    val checked = (inputs[key] as? Boolean) ?: initial
    val label = node.string("label")
    Row(
        modifier = Modifier
            .fillMaxWidth()
            .clip(RoundedCornerShape(16.dp))
            .clickable {
                inputs[key] = !checked
                if (node.string("action_id").isNotBlank()) onAction(node.string("action_id"))
            }
            .semantics {
                contentDescription = "$label, ${if (checked) "on" else "off"}"
                role = Role.Switch
            }
            .padding(vertical = 10.dp),
        verticalAlignment = Alignment.CenterVertically,
    ) {
        Text(label, color = MaterialTheme.colorScheme.onSurface, modifier = Modifier.weight(1f))
        Box(
            Modifier
                .size(42.dp, 24.dp)
                .clip(RoundedCornerShape(999.dp))
                .background(
                    if (checked) MaterialTheme.colorScheme.secondary
                    else MaterialTheme.colorScheme.surfaceVariant,
                ),
            contentAlignment = if (checked) Alignment.CenterEnd else Alignment.CenterStart,
        ) {
            Box(
                Modifier
                    .padding(3.dp)
                    .size(18.dp)
                    .clip(CircleShape)
                    .background(if (checked) Color.Black else Color.White),
            )
        }
    }
}

@Composable
private fun SurfaceTextInput(node: SurfaceComponent, inputs: MutableMap<String, Any>) {
    val key = node.string("input_key")
    var value by remember(key) {
        mutableStateOf((inputs[key] as? String) ?: node.string("value"))
    }
    Column {
        if (node.string("label").isNotBlank()) {
            Text(
                node.string("label"),
                color = MaterialTheme.colorScheme.onSurface,
                style = MaterialTheme.typography.labelMedium,
            )
        }
        BasicTextField(
            value = value,
            onValueChange = {
                value = it.take(500)
                inputs[key] = value
            },
            textStyle = MaterialTheme.typography.bodyLarge.copy(
                color = MaterialTheme.colorScheme.onSurface,
            ),
            modifier = Modifier
                .fillMaxWidth()
                .padding(top = 6.dp)
                .clip(RoundedCornerShape(16.dp))
                .background(MaterialTheme.colorScheme.surfaceVariant)
                .semantics {
                    contentDescription = node.string("content_description")
                        .ifBlank {
                            node.string("label").ifBlank { node.string("placeholder") }
                        }
                }
                .padding(horizontal = 14.dp, vertical = 12.dp),
            decorationBox = { inner ->
                if (value.isEmpty()) {
                    Text(
                        node.string("placeholder"),
                        color = MaterialTheme.colorScheme.onSurfaceVariant,
                    )
                }
                inner()
            },
        )
    }
}

@Composable
private fun SurfaceDisclosure(node: SurfaceComponent) {
    Column(
        modifier = Modifier
            .fillMaxWidth()
            .clip(RoundedCornerShape(14.dp))
            .background(Color(0xFF10201D))
            .padding(12.dp),
    ) {
        Text(
            node.string("text"),
            color = MaterialTheme.colorScheme.secondary,
            style = MaterialTheme.typography.labelMedium,
        )
        Text(
            node.string("capability"),
            color = MaterialTheme.colorScheme.onSurfaceVariant,
            style = MaterialTheme.typography.labelSmall,
        )
    }
}

@Composable
private fun SurfaceError(node: SurfaceComponent) {
    Text(
        node.string("message").ifBlank { node.string("text") },
        color = MaterialTheme.colorScheme.error,
        modifier = Modifier
            .fillMaxWidth()
            .clip(RoundedCornerShape(14.dp))
            .background(Color(0xFF2A1115))
            .padding(12.dp),
    )
}

private fun org.json.JSONArray.components(): List<SurfaceComponent> =
    buildList {
        for (index in 0 until length()) {
            SurfaceComponent.fromJson(optJSONObject(index))?.let(::add)
        }
    }

private fun spacing(token: String) = when (token) {
    "none" -> 0.dp
    "xs" -> 4.dp
    "sm" -> 8.dp
    "lg" -> 20.dp
    "xl" -> 28.dp
    else -> 12.dp
}

@Composable
private fun tone(token: String): Color = when (token) {
    "secondary" -> MaterialTheme.colorScheme.secondary
    "warning" -> Color(0xFFFFC857)
    "danger" -> MaterialTheme.colorScheme.error
    else -> MaterialTheme.colorScheme.onSurface
}
